name: Build & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Build Linux amd64
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o crunchycleaner .

      - name: Build Linux arm64
        run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o crunchycleaner-arm64 .

      - name: Run CrunchyCleaner Linux
        run: ./crunchycleaner -v

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Build Windows amd64
        run: go build -o crunchycleaner.exe .

      - name: Run CrunchyCleaner Windows
        run: ./crunchycleaner.exe -v
